### PR TITLE
Batch archiving endpoint

### PR DESCRIPTION
**Pull request by Exide**
This is running in iad.dev currently.

### CODE REVIEW

**Comment by Exide** [comment]
Don't merge until #1110 has been merged.

**Comment by Exide** [comment]
I found something I want to change. Closing for now.

**Comment by Exide** [comment]
This should good to merge once #1110 has been merged.

**Comment by lkemmerer** [comment]
closing and replacing with batch-archiving-endpoints branch, which is rebased onto master and has fewer commits.

**Pull request closed without merging**
